image: docker:git

stages:
- build
- deploy

variables:
  CONTAINER_TEST_IMAGE: registry.example.com/my-group/my-project:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.ooo.ua/bulich/bpt-admin:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.ooo.ua

build:
  stage: build
  script:
    - ls
    - pre-admin.sh
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
    - post-admin.sh

deploy:
  stage: deploy
  script:
    - ./deploy.sh
  only:
    - master