stages:
  - build


## build stage

build:
  stage: build
  tags: [deploy]
  script:
    - mkdir -p .ci_status
    - echo "Build"
    - sh pre-admin.sh
    - sh build.sh
    - sh post-admin.sh
    - touch .ci_status/build_success
  artifacts:
    paths:
      - .ci_status/


