version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t bpt-api . --no-cache
      - docker tag bpt-api:latest 893041221537.dkr.ecr.eu-central-1.amazonaws.com/bpt-api:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 893041221537.dkr.ecr.eu-central-1.amazonaws.com/bpt-api:latest