apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bpt-admin-__CI_ENVIRONMENT_SLUG__
  labels:
    name: bpt-admin-__CI_ENVIRONMENT_SLUG__
    commit: __COMMIT__
    env: __CI_ENVIRONMENT_SLUG__
  namespace: bpt
spec:
  replicas: __ADMIN-REPLICA__
  template:
    metadata:
      labels:
        name: bpt-admin-__CI_ENVIRONMENT_SLUG__
        env: __CI_ENVIRONMENT_SLUG__
    spec:
      nodeSelector:
            nodetype: bpt
            apptype: admin
      containers:
      - name: admin
        image: eu.gcr.io/bpt-core/bpt-admin:__VERSION__
        ports:
        - containerPort: 80
        env:
        - name: ENABLE_MONITORING
          value: '1'
        - name: NGINX_WEB_ROOT
          value: '/var/www/html'
        - name: ENVIRONMENT
          value: 'production'
        - name: ATATUS_LICENSE_KEY
          value: 'lic_apm_745449bffe0a444492f65bde195937a8'
        - name: ATATUS_APP_NAME
          value: 'six-app'
        - name: ATATUS_FRAMEWORK
          value: 'Yii2'
        - name: MAX_EXECUTION_TIME
          value: '60'
        - name: PHP_SESSION_TIME
          value: '86400'
        - name: PHP_MEMORY_MAX
          value: '256'
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
      imagePullSecrets:
        - name: gitlab-registry