apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: __CI_ENVIRONMENT_SLUG__
  labels:
    name: bpt-admin
    app: __CI_ENVIRONMENT_SLUG__
    track: stable 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: __CI_ENVIRONMENT_SLUG__
        track: stable
        version: "0.1"
    spec:
      containers:
      - name: bpt-admin
        image: registry.ooo.ua/bulich/bpt-admin:__VERSION__
        imagePullPolicy: Always
        ports:        
          containerPort: 80
      imagePullSecrets:
        - name: gitlab-registry
