apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bpt-admin-__CI_ENVIRONMENT_SLUG__
  labels:
    name: bpt-admin-__CI_ENVIRONMENT_SLUG__
    commit: __COMMIT__
    env: __CI_ENVIRONMENT_SLUG__
  namespace: bpt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: bpt-admin-__CI_ENVIRONMENT_SLUG__
        env: __CI_ENVIRONMENT_SLUG__
    spec:
      nodeSelector:
            ntype: bpt
      containers:
      - name: admin   
        image: registry.ooo.ua/bulich/bpt-admin:__VERSION__        
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: gitlab-registry