apiVersion: v1
kind: ServiceAccount
metadata:
  name: bpt
  namespace: bpt
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bpt-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: bpt
  namespace: bpt
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""