apiVersion: v1
kind: Service
metadata:
  name: bpt-admin
  labels:
    name: bpt-admin
    commit: __COMMIT__
  namespace: bpt
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: bpt-admin