apiVersion: v1
kind: Service
metadata:
  name: bpt-admin
  labels:
    name: bpt-admin
  namespace: bpt
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30082
  selector:
    name: bpt-admin
