apiVersion: v1
kind: Service
metadata:
  name: bpt-admin-__CI_ENVIRONMENT_SLUG__
  labels:
    name: bpt-admin
    prometheus-scrape: "true"
  namespace: bpt
spec:
  type: ClusterIP
  ports:
    # the port that this service should serve on
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: __CI_ENVIRONMENT_SLUG__
