apiVersion: v1
kind: Service
metadata:
  name: bpt-admin
  labels:
    name: bpt-admin
  namespace: bpt
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: bpt-admin
